### ISSUE TITLE
Safeguard against unsupported text encoding.

### ISSUE THREAD

**Issue by shawnbrown** [hillscott/wp-static#1]
I see a comment that reads _"Ensure your file-system supports non-ASCII file-names!"_ but this is something you can enforce programmatically.

By default, the `urllib.parse.unquote()` method encodes to UTF-8 using the "replace" error handling scheme. This could replace certain characters with "?" or other text that doesn't match the intended file name. You can head-off this issue by explicitly converting to the file system encoding and specifying the "strict" error handling scheme:

```python
import sys

fs_encoding = sys.getfilesystemencoding()

   ...

   value = unquote(path, fs_encoding, 'strict')
```

This way, the script will throw an error if there are paths that cannot be accurately represented by the file system encoding (instead of failing silently).

You can find details about supported error handling schemes [here](https://docs.python.org/3/library/codecs.html#error-handlers).

**Comment by hillscott** [comment]
Thanks so much! Your improvement was tested and is now integrated.
